const players = [
    {
        "id": 27,
        "Name": "Tommy DeVito",
        "Position": "QB",
        "Age": 27,
        "Height": "6' 2\"",
        "Weight": "210 lbs",
        "Active": "Questionable",
        "College": "Illinois",
        "Jersey": 16,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 64,
        "Name": "Joshua Dobbs",
        "Position": "QB",
        "Age": 30,
        "Height": "6' 3\"",
        "Weight": "220 lbs",
        "Active": "Active",
        "College": "Tennessee",
        "Jersey": 11,
        "Draft_Year": 2017,
        "Draft_Round": 4,
        "Team": "New England Patriots"
    },
    {
        "id": 29,
        "Name": "Drake Maye",
        "Position": "QB",
        "Age": 23,
        "Height": "6' 4\"",
        "Weight": "225 lbs",
        "Active": "Active",
        "College": "North Carolina",
        "Jersey": 10,
        "Draft_Year": 2024,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {
        "id": 28,
        "Name": "TreVeyon Henderson",
        "Position": "RB",
        "Age": 23,
        "Height": "5' 10\"",
        "Weight": "202 lbs",
        "Active": "Active",
        "College": "Ohio State",
        "Jersey": 32,
        "Draft_Year": 2025,
        "Draft_Round": 2,
        "Team": "New England Patriots"
    },
    {
        "id": 13,
        "Name": "Terrell Jennings",
        "Position": "RB",
        "Age": 24,
        "Height": "6'",
        "Weight": "217 lbs",
        "Active": "Active",
        "College": "Florida A&M",
        "Jersey": 26,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 31,
        "Name": "Rhamondre Stevenson",
        "Position": "RB",
        "Age": 27,
        "Height": "6'",
        "Weight": "227 lbs",
        "Active": "OUT",
        "College": "Oklahoma",
        "Jersey": 38,
        "Draft_Year": 2021,
        "Draft_Round": 4,
        "Team": "New England Patriots"
    },
    {
        "id": 30,
        "Name": "Kayshon Boutte",
        "Position": "WR",
        "Age": 23,
        "Height": "5' 11\"",
        "Weight": "197 lbs",
        "Active": "Questionable",
        "College": "LSU",
        "Jersey": 9,
        "Draft_Year": 2023,
        "Draft_Round": 6,
        "Team": "New England Patriots"
    },
    {
        "id": 43,
        "Name": "Efton Chism III",
        "Position": "WR",
        "Age": 24,
        "Height": "5' 10\"",
        "Weight": "198 lbs",
        "Active": "Active",
        "College": "Eastern Washington",
        "Jersey": 86,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 34,
        "Name": "Stefon Diggs",
        "Position": "WR",
        "Age": 31,
        "Height": "6'",
        "Weight": "191 lbs",
        "Active": "Active",
        "College": "Maryland",
        "Jersey": 8,
        "Draft_Year": 2015,
        "Draft_Round": 5,
        "Team": "New England Patriots"
    },
    {
        "id": 38,
        "Name": "DeMario Douglas",
        "Position": "WR",
        "Age": 24,
        "Height": "5' 8\"",
        "Weight": "192 lbs",
        "Active": "Active",
        "College": "Liberty",
        "Jersey": 3,
        "Draft_Year": 2023,
        "Draft_Round": 6,
        "Team": "New England Patriots"
    },
    {
        "id": 18,
        "Name": "Mack Hollins",
        "Position": "WR",
        "Age": 32,
        "Height": "6' 4\"",
        "Weight": "221 lbs",
        "Active": "Active",
        "College": "North Carolina",
        "Jersey": 13,
        "Draft_Year": 2017,
        "Draft_Round": 4,
        "Team": "New England Patriots"
    },
    {
        "id": 39,
        "Name": "Jalen Hurd",
        "Position": "WR",
        "Age": 29,
        "Height": "6' 5\"",
        "Weight": "230 lbs",
        "Active": "Active",
        "College": "Baylor",
        "Jersey": 13,
        "Draft_Year": 2019,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {
        "id": 82,
        "Name": "Kyle Williams",
        "Position": "WR",
        "Age": 23,
        "Height": "5' 11\"",
        "Weight": "190 lbs",
        "Active": "Active",
        "College": "Washington State",
        "Jersey": 18,
        "Draft_Year": 2025,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {
        "id": 81,
        "Name": "Hunter Henry",
        "Position": "TE",
        "Age": 30,
        "Height": "6' 5\"",
        "Weight": "249 lbs",
        "Active": "Active",
        "College": "Arkansas",
        "Jersey": 85,
        "Draft_Year": 2016,
        "Draft_Round": 2,
        "Team": "New England Patriots"
    },
    {
        "id": 50,
        "Name": "Austin Hooper",
        "Position": "TE",
        "Age": 31,
        "Height": "6' 4\"",
        "Weight": "254 lbs",
        "Active": "Questionable",
        "College": "Stanford",
        "Jersey": 81,
        "Draft_Year": 2016,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {
        "id": 51,
        "Name": "Jack Westover",
        "Position": "TE",
        "Age": 26,
        "Height": "6' 2\"",
        "Weight": "245 lbs",
        "Active": "Active",
        "College": "Washington",
        "Jersey": 37,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 40,
        "Name": "Garrett Bradbury",
        "Position": "C",
        "Age": 30,
        "Height": "6' 3\"",
        "Weight": "300 lbs",
        "Active": "Active",
        "College": "NC State",
        "Jersey": 65,
        "Draft_Year": 2019,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {
        "id": 80,
        "Name": "Ben Brown",
        "Position": "C",
        "Age": 27,
        "Height": "6' 5\"",
        "Weight": "313 lbs",
        "Active": "Active",
        "College": "Ole Miss",
        "Jersey": 77,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 56,
        "Name": "Jared Wilson",
        "Position": "C",
        "Age": 22,
        "Height": "6' 3\"",
        "Weight": "310 lbs",
        "Active": "Active",
        "College": "Georgia",
        "Jersey": 58,
        "Draft_Year": 2025,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {
        "id": 97,
        "Name": "Marcus Bryant",
        "Position": "OT",
        "Age": 23,
        "Height": "6' 7\"",
        "Weight": "320 lbs",
        "Active": "Active",
        "College": "Missouri",
        "Jersey": 52,
        "Draft_Year": 2025,
        "Draft_Round": 7,
        "Team": "New England Patriots"
    },
    {
        "id": 79,
        "Name": "Will Campbell",
        "Position": "OT",
        "Age": 21,
        "Height": "6' 6\"",
        "Weight": "319 lbs",
        "Active": "Active",
        "College": "LSU",
        "Jersey": 66,
        "Draft_Year": 2025,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {
        "id": 58,
        "Name": "Vederian Lowe",
        "Position": "OT",
        "Age": 26,
        "Height": "6' 5\"",
        "Weight": "315 lbs",
        "Active": "Active",
        "College": "Illinois",
        "Jersey": 59,
        "Draft_Year": 2022,
        "Draft_Round": 6,
        "Team": "New England Patriots"
    },
    {
        "id": 57,
        "Name": "Morgan Moses",
        "Position": "OT",
        "Age": 34,
        "Height": "6' 6\"",
        "Weight": "320 lbs",
        "Active": "Active",
        "College": "Virginia",
        "Jersey": 76,
        "Draft_Year": 2014,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {
        "id": 78,
        "Name": "Mike Onwenu",
        "Position": "OT",
        "Age": 27,
        "Height": "6' 3\"",
        "Weight": "350 lbs",
        "Active": "Active",
        "College": "Michigan",
        "Jersey": 71,
        "Draft_Year": 2020,
        "Draft_Round": 6,
        "Team": "New England Patriots"
    },
    {
        "id": 41,
        "Name": "Caedan Wallace",
        "Position": "OT",
        "Age": 25,
        "Height": "6' 5\"",
        "Weight": "314 lbs",
        "Active": "Questionable",
        "College": "Penn State",
        "Jersey": 70,
        "Draft_Year": 2024,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {
        "id": 62,
        "Name": "Milton Williams",
        "Position": "DE",
        "Age": 26,
        "Height": "6' 3\"",
        "Weight": "290 lbs",
        "Active": "Questionable",
        "College": "Louisiana Tech",
        "Jersey": 97,
        "Draft_Year": 2021,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {
        "id": 77,
        "Name": "Christian Barmore",
        "Position": "DT",
        "Age": 26,
        "Height": "6' 5\"",
        "Weight": "315 lbs",
        "Active": "Active",
        "College": "Alabama",
        "Jersey": 90,
        "Draft_Year": 2021,
        "Draft_Round": 2,
        "Team": "New England Patriots"
    },
    {
        "id": 76,
        "Name": "Cory Durden",
        "Position": "DT",
        "Age": 26,
        "Height": "6' 4\"",
        "Weight": "305 lbs",
        "Active": "Active",
        "College": "NC State",
        "Jersey": 94,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 74,
        "Name": "Joshua Farmer",
        "Position": "DT",
        "Age": 22,
        "Height": "6' 3\"",
        "Weight": "312 lbs",
        "Active": "Questionable",
        "College": "Florida State",
        "Jersey": 92,
        "Draft_Year": 2025,
        "Draft_Round": 4,
        "Team": "New England Patriots"
    },
    {
        "id": 75,
        "Name": "Eric Gregory",
        "Position": "DT",
        "Age": 25,
        "Height": "6' 3\"",
        "Weight": "319 lbs",
        "Active": "Active",
        "College": "Arkansas",
        "Jersey": 55,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 98,
        "Name": "Khyiris Tonga",
        "Position": "DT",
        "Age": 29,
        "Height": "6' 2\"",
        "Weight": "335 lbs",
        "Active": "Active",
        "College": "BYU",
        "Jersey": 95,
        "Draft_Year": 2021,
        "Draft_Round": 7,
        "Team": "New England Patriots"
    },
    {
        "id": 95,
        "Name": "K'Lavon Chaisson",
        "Position": "LB",
        "Age": 26,
        "Height": "6' 3\"",
        "Weight": "255 lbs",
        "Active": "Active",
        "College": "LSU",
        "Jersey": 44,
        "Draft_Year": 2020,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {
        "id": 73,
        "Name": "Christian Elliss",
        "Position": "LB",
        "Age": 26,
        "Height": "6' 2\"",
        "Weight": "231 lbs",
        "Active": "Questionable",
        "College": "Idaho",
        "Jersey": 53,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 59,
        "Name": "Jack Gibbens",
        "Position": "LB",
        "Age": 26,
        "Height": "6' 3\"",
        "Weight": "242 lbs",
        "Active": "Active",
        "College": "Minnesota",
        "Jersey": 51,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 96,
        "Name": "Anfernee Jennings",
        "Position": "LB",
        "Age": 28,
        "Height": "6' 2\"",
        "Weight": "255 lbs",
        "Active": "Active",
        "College": "Alabama",
        "Jersey": 33,
        "Draft_Year": 2020,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {
        "id": 2,
        "Name": "Harold Landry III",
        "Position": "LB",
        "Age": 29,
        "Height": "6' 2\"",
        "Weight": "252 lbs",
        "Active": "Active",
        "College": "Boston College",
        "Jersey": 2,
        "Draft_Year": 2018,
        "Draft_Round": 2,
        "Team": "New England Patriots"
    },
    {
        "id": 54,
        "Name": "Marte Mapu",
        "Position": "LB",
        "Age": 26,
        "Height": "6' 3\"",
        "Weight": "230 lbs",
        "Active": "Active",
        "College": "Sacramento State",
        "Jersey": 15,
        "Draft_Year": 2023,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {
        "id": 55,
        "Name": "Caleb Murphy",
        "Position": "LB",
        "Age": 25,
        "Height": "6' 3\"",
        "Weight": "254 lbs",
        "Active": "Active",
        "College": "Ferris State",
        "Jersey": 45,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 48,
        "Name": "Elijah Ponder",
        "Position": "LB",
        "Age": 23,
        "Height": "6' 3\"",
        "Weight": "261 lbs",
        "Active": "Active",
        "College": "Cal Poly",
        "Jersey": 91,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 91,
        "Name": "Robert Spillane",
        "Position": "LB",
        "Age": 29,
        "Height": "6' 1\"",
        "Weight": "229 lbs",
        "Active": "Active",
        "College": "Western Michigan",
        "Jersey": 14,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 17,
        "Name": "Jahlani Tavai",
        "Position": "LB",
        "Age": 29,
        "Height": "6' 2\"",
        "Weight": "255 lbs",
        "Active": "Active",
        "College": "Hawai'i",
        "Jersey": 48,
        "Draft_Year": 2019,
        "Draft_Round": 2,
        "Team": "New England Patriots"
    },
    {
        "id": 16,
        "Name": "Alex Austin",
        "Position": "CB",
        "Age": 24,
        "Height": "6' 1\"",
        "Weight": "191 lbs",
        "Active": "Active",
        "College": "Oregon State",
        "Jersey": 28,
        "Draft_Year": 2023,
        "Draft_Round": 7,
        "Team": "New England Patriots"
    },
    {
        "id": 19,
        "Name": "Carlton Davis III",
        "Position": "CB",
        "Age": 28,
        "Height": "6' 1\"",
        "Weight": "206 lbs",
        "Active": "Active",
        "College": "Auburn",
        "Jersey": 7,
        "Draft_Year": 2018,
        "Draft_Round": 2,
        "Team": "New England Patriots"
    },
    {
        "id": 61,
        "Name": "Christian Gonzalez",
        "Position": "CB",
        "Age": 23,
        "Height": "6' 1\"",
        "Weight": "205 lbs",
        "Active": "Active",
        "College": "Oregon",
        "Jersey": 0,
        "Draft_Year": 2023,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {
        "id": 60,
        "Name": "Marcus Jones",
        "Position": "CB",
        "Age": 27,
        "Height": "5' 8\"",
        "Weight": "188 lbs",
        "Active": "Active",
        "College": "Houston",
        "Jersey": 25,
        "Draft_Year": 2022,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {
        "id": 3,
        "Name": "Charles Woods",
        "Position": "CB",
        "Age": 25,
        "Height": "5' 11\"",
        "Weight": "185 lbs",
        "Active": "Active",
        "College": "SMU",
        "Jersey": 22,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {
        "id": 94,
        "Name": "Jaylinn Hawkins",
        "Position": "S",
        "Age": 28,
        "Height": "6' 1\"",
        "Weight": "208 lbs",
        "Active": "Active",
        "College": "California",
        "Jersey": 21,
        "Draft_Year": 2020,
        "Draft_Round": 4,
        "Team": "New England Patriots"
    },
    {
        "id": 93,
        "Name": "Dell Pettus",
        "Position": "S",
        "Age": 24,
        "Height": "5' 11\"",
        "Weight": "200 lbs",
        "Active": "Active",
        "College": "Troy",
        "Jersey": 24,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {   
        "id": 92,
        "Name": "John Saunders Jr.",
        "Position": "S",
        "Age": 24,
        "Height": "6' 2\"",
        "Weight": "211 lbs",
        "Active": "Active",
        "College": "Ole Miss",
        "Jersey": 23,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {   
        "id": 36,
        "Name": "Brenden Schooler",
        "Position": "S",
        "Age": 28,
        "Height": "6' 2\"",
        "Weight": "210 lbs",
        "Active": "Active",
        "College": "Texas",
        "Jersey": 41,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {   
        "id": 45,
        "Name": "Craig Woodson",
        "Position": "S",
        "Age": 24,
        "Height": "6'",
        "Weight": "200 lbs",
        "Active": "Active",
        "College": "California",
        "Jersey": 31,
        "Draft_Year": 2025,
        "Draft_Round": 4,
        "Team": "New England Patriots"
    },
    {   
        "id": 49,
        "Name": "Andy Borregales",
        "Position": "K",
        "Age": 22,
        "Height": "5' 11\"",
        "Weight": "202 lbs",
        "Active": "Active",
        "College": "Miami",
        "Jersey": 36,
        "Draft_Year": 2025,
        "Draft_Round": 6,
        "Team": "New England Patriots"
    },
    {   
        "id": 15,
        "Name": "Bryce Baringer",
        "Position": "P",
        "Age": 26,
        "Height": "6' 2\"",
        "Weight": "215 lbs",
        "Active": "Active",
        "College": "Michigan State",
        "Jersey": 17,
        "Draft_Year": 2023,
        "Draft_Round": 6,
        "Team": "New England Patriots"
    },
    {   
        "id": 14,
        "Name": "Julian Ashby",
        "Position": "LS",
        "Age": 23,
        "Height": "6' 1\"",
        "Weight": "231 lbs",
        "Active": "Active",
        "College": "Vanderbilt",
        "Jersey": 47,
        "Draft_Year": 2025,
        "Draft_Round": 7,
        "Team": "New England Patriots"
    },
    {   
        "id": 99,
        "Name": "Tom Brady",
        "Position": "QB",
        "Age": 48,
        "Height": "6' 4\"",
        "Weight": "225 lbs",
        "Active": "OUT",
        "College": "Michigan",
        "Jersey": 12,
        "Draft_Year": 2000,
        "Draft_Round": 6,
        "Team": "New England Patriots"
    },
    {   
        "id": 24,
        "Name": "Patrick Mahomes",
        "Position": "QB",
        "Age": 30,
        "Height": "6' 2\"",
        "Weight": "225 lbs",
        "Active": "Active",
        "College": "Texas Tech",
        "Jersey": 15,
        "Draft_Year": 2017,
        "Draft_Round": 1,
        "Team": "Kansas CIty Chiefs"
    },
    {   
        "id": 86,
        "Name": "Peyton Manning",
        "Position": "QB",
        "Age": 49,
        "Height": "6' 5\"",
        "Weight": "230 lbs",
        "Active": "OUT",
        "College": "Tennessee",
        "Jersey": 18,
        "Draft_Year": 1998,
        "Draft_Round": 1,
        "Team": "Indianapolis Colts"
    },
    {   
        "id": 26,
        "Name": "Aaron Rodgers",
        "Position": "QB",
        "Age": 41,
        "Height": "6' 2\"",
        "Weight": "223 lbs",
        "Active": "Active",
        "College": "California",
        "Jersey": 12,
        "Draft_Year": 2005,
        "Draft_Round": 1,
        "Team": "Green Bay Packers"
    },
    {   
        "id": 52,
        "Name": "Joe Montana",
        "Position": "QB",
        "Age": 69,
        "Height": "6' 2\"",
        "Weight": "200 lbs",
        "Active": "OUT",
        "College": "Notre Dame",
        "Jersey": 16,
        "Draft_Year": 1979,
        "Draft_Round": 3,
        "Team": "San Francisco 49ers"
    },
    {   
        "id": 84,
        "Name": "Brett Favre",
        "Position": "QB",
        "Age": 56,
        "Height": "6' 2\"",
        "Weight": "222 lbs",
        "Active": "OUT",
        "College": "Southern Miss",
        "Jersey": 4,
        "Draft_Year": 1991,
        "Draft_Round": 2,
        "Team": "Green Bay Packers"
    },
    {   
        "id": 85,
        "Name": "Drew Brees",
        "Position": "QB",
        "Age": 46,
        "Height": "6'",
        "Weight": "209 lbs",
        "Active": "OUT",
        "College": "Purdue",
        "Jersey": 9,
        "Draft_Year": 2001,
        "Draft_Round": 2,
        "Team": "New Orleans Saints"
    },
    {   
        "id": 37,
        "Name": "Deion Sanders",
        "Position": "CB",
        "Age": 58,
        "Height": "6' 1\"",
        "Weight": "198 lbs",
        "Active": "Questionable",
        "College": "Florida State",
        "Jersey": 21,
        "Draft_Year": 1989,
        "Draft_Round": 1,
        "Team": "Dallas Cowboys"
    },
    {   
        "id": 53,
        "Name": "Jerry Rice",
        "Position": "WR",
        "Age": 63,
        "Height": "6' 2\"",
        "Weight": "200 lbs",
        "Active": "OUT",
        "College": "Mississippi Valley State",
        "Jersey": 80,
        "Draft_Year": 1985,
        "Draft_Round": 1,
        "Team": "San Francisco 49ers"
    },
    {   
        "id": 20,
        "Name": "Rob Gronkowski",
        "Position": "TE",
        "Age": 36,
        "Height": "6' 6\"",
        "Weight": "265 lbs",
        "Active": "OUT",
        "College": "Arizona",
        "Jersey": 87,
        "Draft_Year": 2010,
        "Draft_Round": 2,
        "Team": "New England Patriots"
    },
    {   
        "id": 32,
        "Name": "Travis Kelce",
        "Position": "TE",
        "Age": 36,
        "Height": "6' 5\"",
        "Weight": "250 lbs",
        "Active": "Active",
        "College": "Cincinnati",
        "Jersey": 87,
        "Draft_Year": 2013,
        "Draft_Round": 3,
        "Team": "Kansas CIty Chiefs"
    },
    {   
        "id": 101,
        "Name": "Odell Beckham Jr.",
        "Position": "WR",
        "Age": 33,
        "Height": "5' 11\"",
        "Weight": "200 lbs",
        "Active": "OUT",
        "College": "LSU",
        "Jersey": 13,
        "Draft_Year": 2014,
        "Draft_Round": 1,
        "Team": "New York Giants"
    },
    {   
        "id": 83,
        "Name": "J. J. Watt",
        "Position": "DE",
        "Age": 36,
        "Height": "6' 5\"",
        "Weight": "288 lbs",
        "Active": "OUT",
        "College": "Wisconsin",
        "Jersey": 99,
        "Draft_Year": 2011,
        "Draft_Round": 1,
        "Team": "Houston Texans"
    },
    {   
        "id": 102,
        "Name": "Lamar Jackson",
        "Position": "QB",
        "Age": 28,
        "Height": "6'2\"",
        "Weight": "205 lbs",
        "Active": "Active",
        "College": "\tLouisville",
        "Jersey": 8,
        "Draft_Year": 2018,
        "Draft_Round": 1,
        "Team": "Baltimore Ravens"
    },
    {   
        "id": 25,
        "Name": "Josh Allen",
        "Position": "QB",
        "Age": 29,
        "Height": "6'5\"",
        "Weight": "237 lbs",
        "Active": "Active",
        "College": "Wyoming",
        "Jersey": 17,
        "Draft_Year": 2018,
        "Draft_Round": 1,
        "Team": "Buffalo Bills"
    },
    {   
        "id": 103,
        "Name": "Tyreek Hill",
        "Position": "WR",
        "Age": 31,
        "Height": "5'10\"",
        "Weight": "191 lbs",
        "Active": "Questionable",
        "College": "West Alabama",
        "Jersey": 10,
        "Draft_Year": 2016,
        "Draft_Round": 5,
        "Team": "Miami Dolphins"
    },
    {   
        "id": 87,
        "Name": "Justin Jefferson",
        "Position": "WR",
        "Age": 26,
        "Height": "6'1\"",
        "Weight": "195 lbs",
        "Active": "Active",
        "College": "LSU",
        "Jersey": 18,
        "Draft_Year": 2020,
        "Draft_Round": 1,
        "Team": "Minnesota Vikings"
    },
    {   
        "id": 104,
        "Name": "Walter Payton",
        "Position": "RB",
        "Age": "deceased",
        "Height": "5'10\"",
        "Weight": "200 lbs",
        "Active": "OUT",
        "College": "Jackson State",
        "Jersey": 34,
        "Draft_Year": 1975,
        "Draft_Round": 1,
        "Team": "Chicago Bears"
    },
    {   
        "id": 105,
        "Name": "Barry Sanders",
        "Position": "RB",
        "Age": 57,
        "Height": "5'8\"",
        "Weight": "200 lbs",
        "Active": "OUT",
        "College": "Oklahoma State",
        "Jersey": 20,
        "Draft_Year": 1989,
        "Draft_Round": 1,
        "Team": "Detroit Lions"
    },
    {   
        "id": 106,
        "Name": "Ray Lewis",
        "Position": "LB",
        "Age": 50,
        "Height": "6'1\"",
        "Weight": "240 lbs",
        "Active": "OUT",
        "College": "Miami",
        "Jersey": 52,
        "Draft_Year": 1996,
        "Draft_Round": 1,
        "Team": "Baltimore Ravens"
    },
    {   
        "id": 12,
        "Name": "Julian Edelman",
        "Position": "WR",
        "Age": 39,
        "Height": "5' 10\"",
        "Weight": "198 lbs",
        "Active": "OUT",
        "College": "Kent State",
        "Jersey": 11,
        "Draft_Year": 2009,
        "Draft_Round": 7,
        "Team": "New England Patriots"
    },
    {   
        "id": 107,
        "Name": "Bill Belichick",
        "Position": "C",
        "Age": 73,
        "Height": "6' 2\"",
        "Weight": "215 lbs",
        "Active": "Questionable",
        "College": "Wesleyan University",
        "Jersey": "-",
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "North Carolina"
    },
    {   
        "id": 46,
        "Name": "Randy Moss",
        "Position": "WR",
        "Age": 48,
        "Height": "6' 4\"",
        "Weight": "210 lbs",
        "Active": "OUT",
        "College": "Marshall",
        "Jersey": 81,
        "Draft_Year": 1998,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {   
        "id": 89,
        "Name": "Mac Jones",
        "Position": "QB",
        "Age": 27,
        "Height": "6' 3\"",
        "Weight": "220 lbs",
        "Active": "Active",
        "College": "Alabama",
        "Jersey": 10,
        "Draft_Year": 2021,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {   
        "id": 88,
        "Name": "Wes Welker",
        "Position": "WR",
        "Age": 44,
        "Height": "5' 9\"",
        "Weight": "185 lbs",
        "Active": "Questionable",
        "College": "Texas Tech",
        "Jersey": 83,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {   
        "id": 63,
        "Name": "Vince Wilfork",
        "Position": "DT",
        "Age": 44,
        "Height": "6' 2\"",
        "Weight": "325 lbs",
        "Active": "OUT",
        "College": "Miami",
        "Jersey": 75,
        "Draft_Year": 2004,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {   
        "id": 72,
        "Name": "Ty Law",
        "Position": "CB",
        "Age": 51,
        "Height": "5' 11\"",
        "Weight": "200 lbs",
        "Active": "OUT",
        "College": "Michigan",
        "Jersey": 24,
        "Draft_Year": 1995,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {   
        "id": 44,
        "Name": "Stephon Gilmore",
        "Position": "CB",
        "Age": 35,
        "Height": "6'",
        "Weight": "190 lbs",
        "Active": "OUT",
        "College": "\tSouth Carolina",
        "Jersey": 27,
        "Draft_Year": 2012,
        "Draft_Round": 1,
        "Team": "Buffalo Bills"
    },
    {   
        "id": 108,
        "Name": "Jim Brown",
        "Position": "FB",
        "Age":"deceased",
        "Height": "6' 2\"",
        "Weight": "232 lbs",
        "Active": "OUT",
        "College": "Syracuse",
        "Jersey": 32,
        "Draft_Year": 1957,
        "Draft_Round": 1,
        "Team": "Cleveland Browns"
    },
    {   
        "id": 9,
        "Name": "Lawrence Taylor",
        "Position": "LB",
        "Age": 66,
        "Height": "6' 3\"",
        "Weight": "237 lbs",
        "Active": "OUT",
        "College": "North Carolina",
        "Jersey": 56,
        "Draft_Year": 1981,
        "Draft_Round": 1,
        "Team": "New York Giants"
    },
    {   
        "id": 8,
        "Name": "Antonio Brown",
        "Position": "WR",
        "Age": 37,
        "Height": "5' 10\"",
        "Weight": "185 lbs",
        "Active": "Questionable",
        "College": "Central Michigan",
        "Jersey": 84,
        "Draft_Year": 2010,
        "Draft_Round": 6,
        "Team": "Pittsburgh Steelers"
    },
    {   
        "id": 42,
        "Name": "Troy Polomalu",
        "Position": "S",
        "Age": 44,
        "Height": "5' 10\"",
        "Weight": "207 lbs",
        "Active": "OUT",
        "College": "USC",
        "Jersey": 43,
        "Draft_Year": 2003,
        "Draft_Round": 1,
        "Team": "Pittsburgh Steelers"
    },
    {   
        "id": 109,
        "Name": "Calvin Johnson",
        "Position": "WR",
        "Age": 40,
        "Height": "6' 5\"",
        "Weight": "237 lbs",
        "Active": "OUT",
        "College": "Georgia Tech",
        "Jersey": 81,
        "Draft_Year": 2007,
        "Draft_Round": 1,
        "Team": "Detroit Lions"
    },
    {   
        "id": 47,
        "Name": "Brian Urlacher",
        "Position": "LB",
        "Age": 47,
        "Height": "6' 4\"",
        "Weight": "258 lbs",
        "Active": "OUT",
        "College": "New Mexico",
        "Jersey": 54,
        "Draft_Year": 2000,
        "Draft_Round": 1,
        "Team": "Chicago Bears"
    },
    {   
        "id": 1,
        "Name": "Jason Kelce",
        "Position": "C",
        "Age": 38,
        "Height": "6' 3\"",
        "Weight": "306 lbs",
        "Active": "OUT",
        "College": "Cincinnati",
        "Jersey": 62,
        "Draft_Year": 2011,
        "Draft_Round": 6,
        "Team": "Philadelphia Eagles"
    },
    {   
        "id": 110,
        "Name": "Kendall Fuller",
        "Position": "CB",
        "Age": 30,
        "Height": "5' 11\"",
        "Weight": "198 lbs",
        "Active": "Questionable",
        "College": "Virginia Tech",
        "Jersey": 29,
        "Draft_Year": 2016,
        "Draft_Round": 3,
        "Team": "Washington Commanders"
    },
    {   
        "id": 35,
        "Name": "James Harrison ",
        "Position": "LB",
        "Age": 47,
        "Height": "6'",
        "Weight": "242 lbs",
        "Active": "OUT",
        "College": "Kent State",
        "Jersey": 92,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "Pittsburgh Steelers"
    },
    {   
        "id": 33,
        "Name": "Ben Rothlisberger",
        "Position": "QB",
        "Age": 43,
        "Height": "6' 5\"",
        "Weight": "240 lbs",
        "Active": "OUT",
        "College": "Miami",
        "Jersey": 7,
        "Draft_Year": 2004,
        "Draft_Round": 1,
        "Team": "Pittsburgh Steelers"
    },
    {   
        "id": 7,
        "Name": "Julio Jones",
        "Position": "WR",
        "Age": 36,
        "Height": "6' 3\"",
        "Weight": "220 lbs",
        "Active": "OUT",
        "College": "Alabama",
        "Jersey": 11,
        "Draft_Year": 2011,
        "Draft_Round": 1,
        "Team": "Atlanta Falcons"
    },
    {   
        "id": 11,
        "Name": "Adrian Peterson",
        "Position": "RB",
        "Age": 40,
        "Height": "6' 1\"",
        "Weight": "220 lbs",
        "Active": "OUT",
        "College": "Oklahoma",
        "Jersey": 28,
        "Draft_Year": 2007,
        "Draft_Round": 1,
        "Team": "Minnesota Vikings"
    },
    {   
        "id": 90,
        "Name": "Aj Green",
        "Position": "WR",
        "Age": 37,
        "Height": "6' 4\"",
        "Weight": "207 lbs",
        "Active": "OUT",
        "College": "Georgia",
        "Jersey": 18,
        "Draft_Year": 2011,
        "Draft_Round": 1,
        "Team": "Cincinnati Bengals"
    },
    {   
        "id": 23,
        "Name": "Jimmy Graham",
        "Position": "TE",
        "Age": 38,
        "Height": "6' 7\"",
        "Weight": "265 lbs",
        "Active": "OUT",
        "College": "Miami (FL)",
        "Jersey": 80,
        "Draft_Year": 2010,
        "Draft_Round": 3,
        "Team": "New Orleans Saints"
    },
    {   
        "id": 71,
        "Name": "Myles Garrett",
        "Position": "DE",
        "Age": 29,
        "Height": "6' 4\"",
        "Weight": "272 lbs",
        "Active": "Active",
        "College": "Texas A&M",
        "Jersey": 95,
        "Draft_Year": 2017,
        "Draft_Round": 1,
        "Team": "Cleveland Browns"
    },
    {   
        "id": 6,
        "Name": "Malik Nabers",
        "Position": "WR",
        "Age": 22,
        "Height": "6'",
        "Weight": "200 lbs",
        "Active": "Active",
        "College": "LSU",
        "Jersey": 1,
        "Draft_Year": 2024,
        "Draft_Round": 1,
        "Team": "New York Giants"
    },
    {   
        "id": 5,
        "Name": "Jayden Daniels",
        "Position": "QB",
        "Age": 24,
        "Height": "6' 4\"",
        "Weight": "210 lbs",
        "Active": "Active",
        "College": "LSU",
        "Jersey": 5,
        "Draft_Year": 2024,
        "Draft_Round": 1,
        "Team": "Washington Commanders"
    },
    {   
        "id": 70,
        "Name": "Tedy Bruschi",
        "Position": "LB",
        "Age": 52,
        "Height": "6' 1\"",
        "Weight": "247 lbs",
        "Active": "OUT",
        "College": "Arizona",
        "Jersey": 54,
        "Draft_Year": 1996,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {   
        "id": 22,
        "Name": "Adam Vinatieri",
        "Position": "K",
        "Age": 52,
        "Height": "6'",
        "Weight": "212 lbs",
        "Active": "OUT",
        "College": "South Dakota State",
        "Jersey": 4,
        "Draft_Year": "-",
        "Draft_Round": "-",
        "Team": "New England Patriots"
    },
    {   
        "id": 68,
        "Name": "Willie McGinest",
        "Position": "LB",
        "Age": 53,
        "Height": "6' 5\"",
        "Weight": "270 lbs",
        "Active": "OUT",
        "College": "USC",
        "Jersey": 55,
        "Draft_Year": 1994,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {   
        "id": 69,
        "Name": "Mike Vrabel",
        "Position": "LB",
        "Age": 50,
        "Height": "6' 4\"",
        "Weight": "261 lbs",
        "Active": "Questionable",
        "College": "Ohio State",
        "Jersey": 50,
        "Draft_Year": 1997,
        "Draft_Round": 3,
        "Team": "New England Patriots"
    },
    {   
        "id": 21,
        "Name": "Richard Seymour",
        "Position": "DE",
        "Age": 46,
        "Height": "6' 6\"",
        "Weight": "317 lbs",
        "Active": "OUT",
        "College": "Georgia",
        "Jersey": 93,
        "Draft_Year": 2001,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {   
        "id": 67,
        "Name": "Drew Bledsoe",
        "Position": "QB",
        "Age": 53,
        "Height": "6' 5\"",
        "Weight": "238 lbs",
        "Active": "OUT",
        "College": "Washington State",
        "Jersey": 11,
        "Draft_Year": 1993,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {   
        "id": 10,
        "Name": "Kevin Faulk",
        "Position": "RB",
        "Age": 49,
        "Height": "5' 8\"",
        "Weight": "202 lbs",
        "Active": "Questionable",
        "College": "LSU",
        "Jersey": 33,
        "Draft_Year": 1999,
        "Draft_Round": 2,
        "Team": "New England Patriots"
    },
    {   
        "id": 65,
        "Name": "John Hannah",
        "Position": "G",
        "Age": 74,
        "Height": "6' 2\"",
        "Weight": "265 lbs",
        "Active": "OUT",
        "College": "Alabama",
        "Jersey": 73,
        "Draft_Year": 1973,
        "Draft_Round": 1,
        "Team": "New England Patriots"
    },
    {   
        "id": 66,
        "Name": "Andre Tippett",
        "Position": "LB",
        "Age": 65,
        "Height": "6' 3\"",
        "Weight": "231 lbs",
        "Active": "OUT",
        "College": "Iowa",
        "Jersey": 56,
        "Draft_Year": 1982,
        "Draft_Round": 2,
        "Team": "New England Patriots"
    },
    {   
        "id": 4,
        "Name": "Rodney Harrison",
        "Position": "S",
        "Age": 52,
        "Height": "6' 1\"",
        "Weight": "220 lbs",
        "Active": "OUT",
        "College": "Western Illinois",
        "Jersey": 37,
        "Draft_Year": 1994,
        "Draft_Round": 5,
        "Team": "New England Patriots"
    },
    {   
        "id": 111,
        "Name": "T.J. Watt",
        "Position": "LB",
        "Age": 31,
        "Height": "6' 4\"",
        "Weight": "252 lbs",
        "Active": "Active",
        "College": "Wisconsin",
        "Jersey": 90,
        "Draft_Year": 2017,
        "Draft_Round": 1,
        "Team": "Pittsburgh Steelers"
    },
    {
        "id": 100,
        "Name": "Jordan Shonlie Lublin",
        "Position": "DevOps",
        "Age": 22,
        "Active": "Until Today",
        "College": "Basmach",
        "Jersey": 100,
        "Draft_Year": 2022,
        "Draft_Round": 1,
        "Team": "SPIDER"
    },
]



export default players;
